language: python
python:
    - "2.7"
    - "3.6"
dist: bionic
before_install:
  - sudo add-apt-repository ppa:team-electronics/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install iverilog
  - sudo apt-get install verilator
script: make travis
